[package]
name = "ccipher"
version = "0.1.0"
edition = "2021"
description = "Caesar Cipher encryption/decryption utility."
license = "Unlicense"

[dependencies]
clap = {version = "4.5.20", features = ["derive"]}
testdir = "0.9.1"
