[package]
name = "ccipher"
version = "0.1.0"
edition = "2021"
description = "Caesar Cipher encryption/decryption utility."
license = "Unlicense"

[dependencies]
clap = {version = "4.5.20", features = ["derive"]}
ccipher_io = { path = "../ccipher_io" }
